<?php
/**
 * @file
 * Code for the hsu CAS and More feature.
 */

//include_once 'hsu_cas.features.inc';

define('HSU_CAS_USERNAME_LABEL', 'HSU User ID');

/**
 * Implements hook_boot()
 */
function hsu_cas_boot() {
  global $install_state;
  if (!$install_state) {
    if (isset($_SERVER['PANTHEON_ENVIRONMENT'])) {
      if (!isset($_SERVER['HTTP_X_SSL']) || $_SERVER['HTTP_X_SSL'] != 'ON') {
        header('HTTP/1.0 301 Moved Permanently');
        header('Location: https://' . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI']);
        exit();
      }
    }
  }
}

/**
 * Implements hook_filter_default_formats_alter()
 *
 * THIS REALLY SHOULD BE IN ITS OWN MODULE BUT IM PUTTING IT HERE FOR NOW
 */
if (!function_exists('panopoly_wysiwyg_filter_default_formats_alter')) {
  function panopoly_wysiwyg_filter_default_formats_alter(&$data) {
    // This allows users to enter in more then one extra line
    if (isset($data['panopoly_wysiwyg_text'])) {
      $data['panopoly_wysiwyg_text']['filters']['wysiwyg']['settings']['valid_elements'] .= ',#p';
    }
  }
}

/**
 * Implements hook_update_projects_alter()
 *
 * This function will remove any module managed by hsu WebSpark from
 * the list of modules in the Drupal Update Manager.
 */
function hsu_cas_update_projects_alter(&$projects) {
  // Setup information about managed components to remove from the update managed
  $managed_things = array();
  $managed_things[] = 'kalatheme'; // adding base theme
  $managed_things[] = 'hsu_webspark_bootstrap'; // adding subtheme
  $managed_things[] = 'Innovation'; // adding subtheme
  // WEBSPARK-403, 254 - add modules 1) enabled in openhsu.install file
  $managed_things[] = 'cas'; // CAS library module
  $managed_things[] = 'hsu_cas'; // hsu CAS and More
  // WEBSPARK- - add modules in installation profile and or .make files
  // but not in .info file
    // openhsu.make
  $managed_things[] = 'quicktabs';
  $managed_things[] = 'better_watchdog_ui';
  $managed_things[] = 'admin_menu';
  $managed_things[] = 'feeds_xpathparser';
    // webspark_featurescustom.make
  $managed_things[] = 'email';
  $managed_things[] = 'special_menu_items';
    // hsu_rfi.make
  $managed_things[] = 'multiblock';
  $managed_things[] = 'views_data_export';
  $managed_things[] = 'mimemail';
  $managed_things[] = 'mailsystem';

  // Determine any dependencies to components manged by the distribution
  $profile_info = install_profile_info('openhsu');
  foreach ($profile_info['dependencies'] as $module) {
    $managed_things[] = $module;
    $module_info = drupal_parse_info_file(drupal_get_path('module', $module) . '/' . $module . '.info');
    if (!empty($module_info['dependencies'])) {
      foreach ($module_info['dependencies'] as $dependency) {
        $parts = explode(' (', $dependency, 2);
        $managed_things[] = array_shift($parts);
      }
    }
  }

  // Remove modules and themes managed by distribution
  foreach ($managed_things as $managed_module) {
    unset($projects[$managed_module]);
  }
}

/**
 * Implements hook_update_status_alter()
 *
 * This function will remove any module managed by hsu WebSpark from
 * the list of modules in the Drupal Update Manager.
 */
function hsu_cas_update_status_alter(&$projects) {
  // Don't want to unset this in hook_update_projects_later as per
  // https://drupal.org/node/1875386
  // But we do want to make sure the user isn't aware of updates through the GUI
  // so we mark as always up to date.
  foreach ($projects as $project_name => $project_info) {
    if ($project_name == 'drupal') {
      $projects[$project_name]['status'] = UPDATE_CURRENT;
      $projects[$project_name]['reason'] = t('Drupal core is managed by WebSpark. Do not update manually.');
    }
  }
}

/*
 * Implements hook_menu_alter()
 */
function hsu_cas_menu_alter(&$items) {
  $items['admin/people/cas/create']['title'] = 'Add HSU User';
  $items['user/%user/cas']['access callback'] = FALSE;
  // WEBSPARK-511 - Hide Add hsu degrees link
  $items['node/add/hsu-degree']['access callback'] = FALSE;
}

/*
 * Implements hook_form_id_form_alter()
 */

/* This properly sets the default admin role to 'administrator' and disables all the other roles from being assigned */
function hsu_cas_form_alter(&$form, &$form_state, $form_id) {

  if ($form_id == "user_admin_settings") {
    $roles = array_map('check_plain', user_roles(TRUE));
  }

  /* This function was added to fix CAS role issue by adding CAS role enabled by default and disable it from being unchecked */
  if ($form_id == "cas_admin_settings") {
    $roles = array_map('check_plain', user_roles(TRUE));
    unset($form['account']['cas_auto_assigned_role']);
    $checkbox_authenticated = array(
      '#type' => 'checkbox',
      '#title' => $roles[DRUPAL_AUTHENTICATED_RID],
      '#default_value' => TRUE,
      '#disabled' => TRUE,
    );
    foreach ($roles as $key => $role) {
      // Sets the default administrator role to 'administrator' to ensure CAS role does not become default
      if ($role == "CAS") {
        $name = $role;
        $rid = $key;
      }
    }
    // Preventing CAS role from being taken away from CAS user
    $cas_authenticated = array(
      '#type' => 'checkbox',
      '#title' => $name,
      '#default_value' => TRUE,
      '#disabled' => TRUE,
    );
    unset($roles[DRUPAL_AUTHENTICATED_RID]);
    unset($roles[$rid]);

    // Auto assigns CAS user role to all new CAS users
    $form['account']['cas_auto_assigned_role'] = array(
      '#type' => 'checkboxes',
      '#title' => t('Roles'),
      '#description' => t('The selected roles will be automatically assigned to each CAS user on login. Use this to automatically give CAS users additional privileges or to identify CAS users to other modules.'),
      '#default_value' => variable_get('cas_auto_assigned_role', array()),
      '#options' => $roles,
      '#access' => user_access('administer permissions'),
      DRUPAL_AUTHENTICATED_RID => $checkbox_authenticated,
      $rid => $cas_authenticated,
    );
  }
}

function hsu_cas_form_cas_add_user_form_alter(&$form, &$form_state) {
  $form['account']['cas_name']['#title'] = HSU_CAS_USERNAME_LABEL;
  $form['account']['cas_name']['#description'] = t("Registration will proceed as if the user with the specified @label just logged in.", array('@label' => HSU_CAS_USERNAME_LABEL));
}


function hsu_cas_form_user_register_form_alter(&$form, &$form_state) {
  if (user_access('administer users')) {
    $form['account']['cas_name']['#title'] = HSU_CAS_USERNAME_LABEL;
    $form['account']['cas_name']['#description'] = 'If necessary, additional hsuRITE User IDs can be added after the account is created.';
  }
}

function hsu_cas_form_cas_user_add_alter(&$form, &$form_state) {
  $form['cas_name']['#title'] = HSU_CAS_USERNAME_LABEL;
  $form['actions']['submit'] = array(
    '#type' => 'submit',
    '#value' => t("Add an @label", array('@label' => HSU_CAS_USERNAME_LABEL))
  );
}

function hsu_cas_form_user_profile_form_alter(&$form, &$form_state) {
  if (user_access('administer users')) {
    $form['account']['cas_name']['#title'] = HSU_CAS_USERNAME_LABEL;
    $form['account']['cas_name']['#description'] = '';
  }
}

